name: CI/CD Pipeline

# Trigger the workflow when code is pushed to the master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Copy code to EC2
      run: scp -i /home/tk-lpt-395/Documents/TUTORIAL/AWS/AWS FREE TIER LEARNING/Learning.pem -r ./* ec2-user@ec2-54-90-149-96.compute-1.amazonaws.com:/home/ec2-user/djangoJS/djangoJS

    - name: Deploy the code
      run: ssh -i /home/tk-lpt-395/Documents/TUTORIAL/AWS/AWS FREE TIER LEARNING/Learning.pem ec2-user@ec2-54-90-149-96.compute-1.amazonaws.com 'cd /home/ec2-user/djangoJS/djangoJS && sudo systemctl restart gunicorn && sudo systemctl restart nginx'